### ISSUE TITLE
Error in make analyze

### ISSUE THREAD

**Issue by smruti241** [broadinstitute/pyro-cov#60]
Hi @barkasn , @martinjankowiak , @JacobLemieux , @bkotzen , @corneliusroemer. @fritzo ,
I am using make analyze command for analyzing the data but it is giving me error. The error is:
(genslm) smrutip@dgx1:~/smruti_project/pyro-cov$ make analyze
python scripts/mutrans.py --vary-holdout
Traceback (most recent call last):
  File "/raid/home/smrutip/smruti_project/pyro-cov/scripts/mutrans.py", line 16, in <module>
    from pyrocov import mutrans, pangolin, sarscov2
  File "/raid/home/smrutip/smruti_project/pyro-cov/pyrocov/mutrans.py", line 37, in <module>
    import pyrocov.geo
  File "/raid/home/smrutip/smruti_project/pyro-cov/pyrocov/geo.py", line 12, in <module>
    import pandas as pd
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pandas/__init__.py", line 48, in <module>
    from pandas.core.api import (
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 76, in <module>
    from pandas.core.frame import DataFrame
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pandas/core/frame.py", line 172, in <module>
    from pandas.core.generic import NDFrame
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pandas/core/generic.py", line 169, in <module>
    from pandas.core.window import (
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pandas/core/window/ewm.py", line 15, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pandas/_libs/window/aggregations.cpython-39-x86_64-linux-gnu.so)
make: *** [Makefile:63: analyze] Error 1

Please let me know how to rectify it? Thanks!

**Comment by bkotzen** [comment]
It sounds like you need to upgrade libstdc++6. Does this work? https://github.com/lhelontra/tensorflow-on-arm/issues/13#issuecomment-418202182

**Comment by smruti241** [comment]
but I cant use sudo as I have no access to that in the server. How to deal without sudo?

**Comment by bkotzen** [comment]
You might try downloading from source, https://packages.debian.org/sid/libstdc++6, but if you don't have access to sudo because there are administrators who are regulating sudo permissions the best thing to do is probably to get in touch with these administrators. 

You can also try spinning up a virtual machine through Google Cloud Platform (or another provider), as they have some standardized machines that make sure your environment is suitable for GPU-based tensor computations. You would have to pay for one of these instances, though. I have some documentation on how to do this with Google Cloud Platform if you decide to go down this route.

**Comment by smruti241** [comment]
@bkotzen it didnt help me. Thanks for your suggestion.

**Comment by smruti241** [comment]
Hi @barkasn , @martinjankowiak , @JacobLemieux , @bkotzen , @corneliusroemer. @fritzo ,
I am again using make analyze command for analyzing the data but it is giving me another error. The error is:

`python scripts/mutrans.py --vary-holdout
     1180 Config: ('coef_scale=0.05', 'reparam-localinit', 'full', 10001, 0.05, 0.1, 10.0, 200, 6, None, ())
     1181 loading cached results/mutrans.data.single.5000.1.50.None.pt
     3174 Fitting full guide via SVI
     3178 init stddev = 4.21
     4846 Model has 16747 latent variables of shapes:
 rate_scale ()
 init_scale ()
 rate_loc_scale ()
 init_loc_scale ()
 coef_decentered (3622,)
 init_loc_decentered (3335,)
 pc_rate_decentered (4893,)
 pc_init_decentered (4893,)
     4846 Guide has 3386519 parameters of shapes:
 coef_centered (3622,)
 init_loc_centered ()
 pc_rate_centered ()
 pc_init_centered ()
 AutoLowRankMultivariateNormal.loc (16747,)
 AutoLowRankMultivariateNormal.scale (16747,)
 AutoLowRankMultivariateNormal.cov_factor (16747, 200)
     4889 step    0 L=342.134 RS=0.00951 IS=0.951 RLS=0.0105 ILS=1.05
     9011 step  100 L=46.438 RS=0.0494 IS=0.847 RLS=0.00893 ILS=7.1
    12972 step  200 L=41.7411 RS=0.0676 IS=0.674 RLS=0.0184 ILS=17.2
    17016 step  300 L=26.5829 RS=0.0822 IS=0.751 RLS=0.0219 ILS=22
    21381 step  400 L=24.6947 RS=0.0905 IS=0.455 RLS=0.0225 ILS=25.2
    25999 step  500 L=21.3677 RS=0.125 IS=0.424 RLS=0.0255 ILS=33.6
    29166 step  600 L=19.686 RS=0.15 IS=0.324 RLS=0.0223 ILS=42.2
    33258 step  700 L=18.8145 RS=0.168 IS=0.241 RLS=0.0199 ILS=51.8
    37352 step  800 L=19.681 RS=0.179 IS=0.207 RLS=0.0186 ILS=66.4
    41406 step  900 L=19.2646 RS=0.179 IS=0.175 RLS=0.02 ILS=74.2
    45483 step 1000 L=19.4619 RS=0.173 IS=0.121 RLS=0.0301 ILS=79
    49527 step 1100 L=19.4714 RS=0.172 IS=0.111 RLS=0.0135 ILS=88.5
    53558 step 1200 L=19.729 RS=0.164 IS=0.117 RLS=0.0184 ILS=95
    57531 step 1300 L=19.9648 RS=0.157 IS=0.113 RLS=0.0204 ILS=101
    63090 step 1400 L=20.4755 RS=0.157 IS=0.0984 RLS=0.0207 ILS=114
    67001 step 1500 L=20.5574 RS=0.143 IS=0.102 RLS=0.0284 ILS=117
    71161 step 1600 L=21.0111 RS=0.14 IS=0.11 RLS=0.0188 ILS=130
    75130 step 1700 L=22.309 RS=0.138 IS=0.115 RLS=0.0177 ILS=147
    79155 step 1800 L=22.1498 RS=0.14 IS=0.101 RLS=0.0128 ILS=170
    83159 step 1900 L=22.1456 RS=0.131 IS=0.105 RLS=0.0213 ILS=180
    86005 step 2000 L=22.5603 RS=0.128 IS=0.106 RLS=0.0179 ILS=197
    89574 step 2100 L=23.3498 RS=0.119 IS=0.095 RLS=0.0154 ILS=208
    93570 step 2200 L=23.573 RS=0.112 IS=0.0944 RLS=0.0235 ILS=232
    97565 step 2300 L=23.9607 RS=0.106 IS=0.0965 RLS=0.016 ILS=250
   101630 step 2400 L=24.1473 RS=0.104 IS=0.0951 RLS=0.0164 ILS=285
   105597 step 2500 L=24.9862 RS=0.102 IS=0.0814 RLS=0.0122 ILS=333
   109553 step 2600 L=25.3726 RS=0.101 IS=0.0853 RLS=0.0183 ILS=383
    113505 step 2700 L=25.7136 RS=0.0979 IS=0.0783 RLS=0.0219 ILS=441
   117498 step 2800 L=27.2888 RS=0.0835 IS=0.0708 RLS=0.0231 ILS=482
   121483 step 2900 L=28.3656 RS=0.0802 IS=0.0778 RLS=0.0166 ILS=548
   123892 step 3000 L=29.7852 RS=0.0765 IS=0.069 RLS=0.0197 ILS=662
   127889 step 3100 L=29.4496 RS=0.0727 IS=0.071 RLS=0.0195 ILS=732
   131911 step 3200 L=31.2251 RS=0.0631 IS=0.0716 RLS=0.0151 ILS=846
   135892 step 3300 L=33.4669 RS=0.0649 IS=0.0654 RLS=0.0187 ILS=1.12e+03
   140021 step 3400 L=36.9151 RS=0.0569 IS=0.0484 RLS=0.0147 ILS=1.37e+03
   145413 step 3500 L=38.8946 RS=0.0508 IS=0.0485 RLS=0.017 ILS=1.54e+03
   149501 step 3600 L=48.3159 RS=0.0449 IS=0.046 RLS=0.0186 ILS=1.68e+03
   153492 step 3700 L=48.684 RS=0.0433 IS=0.0495 RLS=0.022 ILS=1.8e+03
   157488 step 3800 L=49.0566 RS=0.0393 IS=0.0505 RLS=0.0164 ILS=2.29e+03
   161488 step 3900 L=60.1267 RS=0.0322 IS=0.0437 RLS=0.0161 ILS=2.67e+03
   165485 step 4000 L=59.5278 RS=0.0307 IS=0.0432 RLS=0.0236 ILS=2.7e+03
   169461 step 4100 L=58.2205 RS=0.028 IS=0.0357 RLS=0.0197 ILS=2.75e+03
   173451 step 4200 L=69.6245 RS=0.0263 IS=0.0343 RLS=0.0181 ILS=3.11e+03
   177409 step 4300 L=58.5717 RS=0.0268 IS=0.0316 RLS=0.0185 ILS=2.64e+03
   181380 step 4400 L=57.9208 RS=0.0262 IS=0.0371 RLS=0.0179 ILS=2.36e+03
   185437 step 4500 L=59.1351 RS=0.0281 IS=0.0375 RLS=0.0191 ILS=2.57e+03
   189495 step 4600 L=55.5876 RS=0.0251 IS=0.0362 RLS=0.0182 ILS=2.66e+03
   193523 step 4700 L=51.9947 RS=0.0246 IS=0.047 RLS=0.0169 ILS=2.51e+03
   197568 step 4800 L=63.8606 RS=0.0267 IS=0.0448 RLS=0.0194 ILS=3.06e+03
   201607 step 4900 L=60.5706 RS=0.0245 IS=0.0367 RLS=0.0198 ILS=3.12e+03
   205969 step 5000 L=58.8764 RS=0.0241 IS=0.045 RLS=0.0175 ILS=3.04e+03
   209664 step 5100 L=56.4454 RS=0.0236 IS=0.045 RLS=0.0164 ILS=2.9e+03
   213678 step 5200 L=56.5097 RS=0.0227 IS=0.0485 RLS=0.0209 ILS=2.83e+03
   217732 step 5300 L=51.059 RS=0.0241 IS=0.0503 RLS=0.0202 ILS=2.64e+03
   222067 step 5400 L=53.7581 RS=0.0234 IS=0.0517 RLS=0.0189 ILS=2.54e+03
   225775 step 5500 L=53.1494 RS=0.0234 IS=0.0555 RLS=0.0235 ILS=2.6e+03
   229784 step 5600 L=52.8454 RS=0.0222 IS=0.0501 RLS=0.0239 ILS=2.81e+03
   233969 step 5700 L=59.0566 RS=0.0226 IS=0.0551 RLS=0.0244 ILS=3.11e+03
Traceback (most recent call last):
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/nn/module.py", line 449, in __call__
    result = super().__call__(*args, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/infer/autoguide/guides.py", line 761, in forward
    latent = self.sample_latent(*args, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/infer/autoguide/guides.py", line 714, in sample_latent
    pos_dist = self.get_posterior(*args, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/infer/autoguide/guides.py", line 1024, in get_posterior
    return dist.LowRankMultivariateNormal(self.loc, cov_factor, cov_diag)
File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/distributions/distribution.py", line 24, in __call__
    return super().__call__(*args, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/torch/distributions/lowrank_multivariate_normal.py", line 112, in __init__
    super(LowRankMultivariateNormal, self).__init__(batch_shape, event_shape,
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/torch/distributions/distribution.py", line 56, in __init__
    raise ValueError(
ValueError: Expected parameter cov_factor (Tensor of shape (16747, 200)) of distribution LowRankMultivariateNormal(loc: torch.Size([16747]), cov_factor: torch.Size([16747, 200]), cov_diag: torch.Size([16747])) to satisfy the constraint IndependentConstraint(Real(), 2), but found invalid values:
tensor([[ 9.3633e-07,  6.5832e-07,  4.4713e-06,  ..., -1.0520e-05,
          2.2387e-06,  3.1975e-06],
        [ 2.6987e-04, -1.1895e-04,  4.1769e-04,  ...,  4.4252e-04,
         -1.5857e-05,  3.8254e-04],
        [ 2.6738e-01,  4.4053e-02,  4.2251e-02,  ..., -7.5441e-02,
         -1.1192e-02,  1.0839e-01],
        ...,
        [-1.2834e-02,  1.0913e-02,  1.8561e-02,  ..., -1.5100e-02,
          2.1953e-02,  2.0999e-02],
        [ 2.1516e-02,  1.0938e-02,  1.3517e-03,  ...,  1.1552e-02,
         -2.8047e-02,  3.4839e-02],
        [-1.6592e-02,  4.9079e-02, -6.2814e-02,  ..., -3.8863e-02,
          1.6868e-02, -1.7376e-02]], grad_fn=<MulBackward0>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/raid/home/smrutip/smruti_project/pyro-cov/scripts/mutrans.py", line 663, in <module>
    main(args)
  File "/raid/home/smrutip/smruti_project/pyro-cov/scripts/mutrans.py", line 581, in main
    result = fit_svi(args, dataset, *config)
  File "/raid/home/smrutip/smruti_project/pyro-cov/scripts/mutrans.py", line 40, in cached_fn
    result = fn(*args, **kwargs)
  File "/raid/home/smrutip/smruti_project/pyro-cov/scripts/mutrans.py", line 131, in fit_svi
    result = mutrans.fit_svi(
  File "/raid/home/smrutip/smruti_project/pyro-cov/pyrocov/mutrans.py", line 887, in fit_svi
    loss = svi.step(dataset=dataset, model_type=model_type)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/infer/svi.py", line 145, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/infer/trace_elbo.py", line 140, in loss_and_grads
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/infer/elbo.py", line 237, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/infer/trace_elbo.py", line 57, in _get_trace
    model_trace, guide_trace = get_importance_trace(
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/infer/enum.py", line 60, in get_importance_trace
    guide_trace = poutine.trace(guide, graph_type=graph_type).get_trace(
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/poutine/trace_messenger.py", line 198, in get_trace
    self(*args, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/poutine/trace_messenger.py", line 180, in __call__ raise exc from e
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/nn/module.py", line 449, in __call__
    result = super().__call__(*args, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/infer/autoguide/guides.py", line 761, in forward
    latent = self.sample_latent(*args, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/infer/autoguide/guides.py", line 714, in sample_latent
    pos_dist = self.get_posterior(*args, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/infer/autoguide/guides.py", line 1024, in get_posterior
    return dist.LowRankMultivariateNormal(self.loc, cov_factor, cov_diag)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/pyro/distributions/distribution.py", line 24, in __call__
    return super().__call__(*args, **kwargs)
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/torch/distributions/lowrank_multivariate_normal.py", line 112, in __init__
    super(LowRankMultivariateNormal, self).__init__(batch_shape, event_shape,
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/torch/distributions/distribution.py", line 56, in __init__
    raise ValueError(
ValueError: Expected parameter cov_factor (Tensor of shape (16747, 200)) of distribution LowRankMultivariateNormal(loc: torch.Size([16747]), cov_factor: torch.Size([16747, 200]), cov_diag: torch.Size([16747])) to satisfy the constraint IndependentConstraint(Real(), 2), but found invalid values:
tensor([[ 9.3633e-07,  6.5832e-07,  4.4713e-06,  ..., -1.0520e-05,
          2.2387e-06,  3.1975e-06],
        [ 2.6987e-04, -1.1895e-04,  4.1769e-04,  ...,  4.4252e-04,
         -1.5857e-05,  3.8254e-04],
        [ 2.6738e-01,  4.4053e-02,  4.2251e-02,  ..., -7.5441e-02,
         -1.1192e-02,  1.0839e-01],
        ...,
        [-1.2834e-02,  1.0913e-02,  1.8561e-02,  ..., -1.5100e-02,
          2.1953e-02,  2.0999e-02],
        [ 2.1516e-02,  1.0938e-02,  1.3517e-03,  ...,  1.1552e-02,
         -2.8047e-02,  3.4839e-02],
        [-1.6592e-02,  4.9079e-02, -6.2814e-02,  ..., -3.8863e-02,
          1.6868e-02, -1.7376e-02]], grad_fn=<MulBackward0>)
                           Trace Shapes:
                            Param Sites:
     AutoLowRankMultivariateNormal.scale       16747
AutoLowRankMultivariateNormal.cov_factor 16747   200
       AutoLowRankMultivariateNormal.loc       16747
                           Sample Sites:
make: *** [Makefile:63: analyze] Error 1`

Please help me in this how to rectify this error. I am not able to correct it. Thanks!!!

**Comment by Jialu-Zuo** [comment]
Hi @barkasn , @martinjankowiak , @JacobLemieux , @bkotzen , @corneliusroemer. @fritzo ,I have the same error as @smruti241's second error and don't know how to figure it out. I'm  looking forward to your reply.

**Comment by bkotzen** [comment]
Hi @Jialu-Zuo, and sorry for missing this @smruti241 - maybe you figured out a solution to this already? I can't say 100% what is causing this error, but I wonder if it may be due to the learning rate being too large. I have found that using a learning rate of 0.01 has been helpful. This can be adjusted by editing line 640 of scripts/mutrans.py, or you can pass the command line argument `-lr=0.01` by adding that to line 63 of Makefile.

**Comment by martinjankowiak** [comment]
that does indeed look like an optimization issue so lowering the learning rate should help. though i'd try to lower the learning rate as little as possible, e.g. `0.03` (i believe the default is `0.05`), and possibly increase the number of optimization iterations to compensate (`"--num-steps"`)

**Comment by Jialu-Zuo** [comment]
@bkotzen, @martinjankowiak,thanks a lot for your reply, it does help a lot. Actually, I have encounterd another problem while preprocessing. As the picture shows, when I try to prune tree with max_num_clades=2000,3000,5000 and 10000 respectively, I find that the produced .pb files can't match with 5000 and 10000, which means both of them just give back a number around 3000 like 3259. I guess it is resulted from  the code "max_num_clades = min(max_num_clades, len(coarse_to_fine))" in line 339 of scripts/preprocess_usher.py where len(coarse_to_fine) = 3259. Therefore, I just delete 5000 and 10000, and change "max-num-clades=5000"  to "max-num-clades=3000" in line 632 of scripts/mutrains.py  , but I don't konw if it is accessible because I see that you updated from 3000 clades to 5000 clades 6 months ago.
![屏幕截图 2023-12-13 111551](https://github.com/broadinstitute/pyro-cov/assets/149792876/3e20ec26-c4a9-4781-8918-c467c2033002)

**Comment by bkotzen** [comment]
Yes, this is correct. I have wondered if line 339 of `scripts/preprocess_usher.py` should use `max` or `min`, but as it stands right now, the contents of columns.5000 and columns.10000 are identical, with the data broken down into 3259 distinct clades. It is fine to move ahead with max_num_clades=5000 for make analyze, as this will load in the columns.5000 file, which is completely functional, it actually has 3259 clades though.

**Comment by Jialu-Zuo** [comment]
Thanks for your explaining!

在 2023-12-14 03:09:14，Ben Kotzen ***@***.***> 写道：

Yes, this is correct. I have wondered if line 339 of scripts/preprocess_usher.py should use max or min, but as it stands right now, the contents of columns.5000 and columns.10000 are identical, with the data broken down into 3259 distinct clades. It is fine to move ahead with max_num_clades=5000 for make analyze, as this will load in the columns.5000 file, which is completely functional, it actually has 3259 clades though.

**Comment by smruti241** [comment]
Hi @barkasn , @martinjankowiak , @JacobLemieux , @bkotzen , @corneliusroemer. @fritzo , I found one more error while running this code:
431147 saving results/mutrans.svi.5000.1.50.coef_scale=0.05.reparam-localinit.full.10001.0.01.0.1.10.0.200.6.None.exclude=___location_____Europe____.pt
   431208 Dense data has shape 105 x 2 x 3335 totaling 335 sequences
   431208 |μ|/σ [median,max] = [0.0414,0.243]
   431209 ΔlogR(S:D614G) = 5.04e-05 ± 0.00
   431209 ΔlogR(S:N501Y) = -4.68e-05 ± 0.00
   431209 ΔlogR(S:E484K) = -5.54e-05 ± 0.00
   431209 ΔlogR(S:L452R) = -1.81e-05 ± 0.00
   431210 R(B.1.1.7)/R(A) = 0.926
   431210 R(B.1.617.2)/R(A) = 0.979
   431211 R(AY.23.1)/R(A) = 1
   431212 KL = 0.06191, MAE = 0.0416, RMSE = 0.1305
   431541 Loaded 1143 x 3631 daily case data, totaling 780372864.0
   431541 Joining GISAID and JHU region codes
   431628 Matching 2 GISAID regions to 3631 JHU fuzzy regions
Traceback (most recent call last):
  File "/raid/home/smrutip/smruti_project/pyro-cov/scripts/mutrans.py", line 663, in <module>
    main(args)
  File "/raid/home/smrutip/smruti_project/pyro-cov/scripts/mutrans.py", line 614, in main
    mutrans.log_holdout_stats({k[-1]: v for k, v in results.items()})
  File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/raid/home/smrutip/smruti_project/pyro-cov/pyrocov/mutrans.py", line 1081, in log_holdout_stats
    medians.append(fit["median"]["coef"][idx] * 0.01)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
make: *** [Makefile:63: analyze] Error 1

can someone please explain me how to rectify this?

**Comment by Jialu-Zuo** [comment]
I figured it out by adding fit[‘median’][‘coef’] = fit[‘median’][‘coef’].to(idx.device) before medians.append(fit["median"]["coef"][idx] * 0.01) in pyrocov/mutrans.py, but I'm not sure if it is correct.

发件人：Smruti Panda ***@***.***>
发送日期：2023-12-14 18:27:47
收件人：broadinstitute/pyro-cov ***@***.***>
抄送人：Jialu-Zuo ***@***.***>,Mention ***@***.***>
主题：Re: [broadinstitute/pyro-cov] Error in make analyze (Issue #60)

Hi @barkasn , @martinjankowiak , @JacobLemieux , @bkotzen , @corneliusroemer. @fritzo , I found one more error while running this code:
 431147 saving results/mutrans.svi.5000.1.50.coef_scale=0.05.reparam-localinit.full.10001.0.01.0.1.10.0.200.6.None.exclude=location_____Europe_.pt
 431208 Dense data has shape 105 x 2 x 3335 totaling 335 sequences
 431208 |μ|/σ [median,max] = [0.0414,0.243]
 431209 ΔlogR(S:D614G) = 5.04e-05 ± 0.00
 431209 ΔlogR(S:N501Y) = -4.68e-05 ± 0.00
 431209 ΔlogR(S:E484K) = -5.54e-05 ± 0.00
 431209 ΔlogR(S:L452R) = -1.81e-05 ± 0.00
 431210 R(B.1.1.7)/R(A) = 0.926
 431210 R(B.1.617.2)/R(A) = 0.979
 431211 R(AY.23.1)/R(A) = 1
 431212 KL = 0.06191, MAE = 0.0416, RMSE = 0.1305
 431541 Loaded 1143 x 3631 daily case data, totaling 780372864.0
 431541 Joining GISAID and JHU region codes
 431628 Matching 2 GISAID regions to 3631 JHU fuzzy regions
 Traceback (most recent call last):
 File "/raid/home/smrutip/smruti_project/pyro-cov/scripts/mutrans.py", line 663, in
 main(args)
 File "/raid/home/smrutip/smruti_project/pyro-cov/scripts/mutrans.py", line 614, in main
 mutrans.log_holdout_stats({k[-1]: v for k, v in results.items()})
 File "/raid/home/smrutip/anaconda3/envs/genslm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
 return func(*args, **kwargs)
 File "/raid/home/smrutip/smruti_project/pyro-cov/pyrocov/mutrans.py", line 1081, in log_holdout_stats
 medians.append(fit["median"]["coef"][idx] * 0.01)
 RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
 make: *** [Makefile:63: analyze] Error 1
can someone please explain me how to rectify this?

**Comment by smruti241** [comment]
@Jialu-Zuo let me check once with your answer. Thanks!!

**Comment by smruti241** [comment]
The command is working now. Thanks @Jialu-Zuo

**Comment by smruti241** [comment]
can anyone please tell me, 'Make analyze' command will take how much time? it is running since yesterday.

**Comment by smruti241** [comment]
for me its completed in 3-4 days. I am closing this issue. Thanks all for helping me out!
